// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlexBackend.Infrastructure;

namespace PlexBackend.Infrastructure.Migrations
{
    [DbContext(typeof(PlexContext))]
    [Migration("20211104105047_MakeStudentChoiceGuidDatabaseGen")]
    partial class MakeStudentChoiceGuidDatabaseGen
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PlexBackend.Core.ContextModels.StudentChoice", b =>
                {
                    b.Property<Guid>("StudentChoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PriorityRank")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("StudentPCN")
                        .HasColumnType("int");

                    b.HasKey("StudentChoiceId");

                    b.ToTable("StudentChoices");
                });
#pragma warning restore 612, 618
        }
    }
}
