version: '3.3'
services:
  plex.db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
    container_name: plex.db
