name: dotnet testing

on:
  push:
    branches:
      - "**" #matches every branch
  pull_request:
    branches:
      - "**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/PlexBackend.WebApi/PlexBackend.WebApi.csproj
    - name: Build
      run: dotnet build ./src/PlexBackend.WebApi/PlexBackend.WebApi.csproj --no-restore
    - name: Test
      run: dotnet test ./tests/PlexBackend.Core.UnitTests/PlexBackend.Core.UnitTests.csproj --no-build --verbosity normal
